/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/src/app/admin/DashboardFiltro`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/modules/cliente/cliente.service`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/modules/cliente/cliente.controller`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/modules/cliente/cliente.module`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/cozinha` | `/cozinha`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/estoque` | `/estoque`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/novo-pedido` | `/novo-pedido`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/pedidos` | `/pedidos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(cliente)'}/cardapio` | `/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(cliente)'}/fiado` | `/fiado`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/src/app/admin/DashboardFiltro`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/modules/cliente/cliente.service`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/modules/cliente/cliente.controller`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/modules/cliente/cliente.module`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/cozinha` | `/cozinha`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/estoque` | `/estoque`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/novo-pedido` | `/novo-pedido`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/pedidos` | `/pedidos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(cliente)'}/cardapio` | `/cardapio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(cliente)'}/fiado` | `/fiado`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../../web/src/app/admin/DashboardFiltro${`?${string}` | `#${string}` | ''}` | `/../../api/src/modules/cliente/cliente.service${`?${string}` | `#${string}` | ''}` | `/../../api/src/modules/cliente/cliente.controller${`?${string}` | `#${string}` | ''}` | `/../../api/src/modules/cliente/cliente.module${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${'/(tabs)'}/cozinha${`?${string}` | `#${string}` | ''}` | `/cozinha${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${'/(tabs)'}/estoque${`?${string}` | `#${string}` | ''}` | `/estoque${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${'/(tabs)'}/novo-pedido${`?${string}` | `#${string}` | ''}` | `/novo-pedido${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${'/(tabs)'}/pedidos${`?${string}` | `#${string}` | ''}` | `/pedidos${`?${string}` | `#${string}` | ''}` | `${'/(cliente)'}/cardapio${`?${string}` | `#${string}` | ''}` | `/cardapio${`?${string}` | `#${string}` | ''}` | `${'/(cliente)'}/fiado${`?${string}` | `#${string}` | ''}` | `/fiado${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/src/app/admin/DashboardFiltro`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/modules/cliente/cliente.service`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/modules/cliente/cliente.controller`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/modules/cliente/cliente.module`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/cozinha` | `/cozinha`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/estoque` | `/estoque`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/novo-pedido` | `/novo-pedido`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}${'/(tabs)'}/pedidos` | `/pedidos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(cliente)'}/cardapio` | `/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(cliente)'}/fiado` | `/fiado`; params?: Router.UnknownInputParams; };
    }
  }
}
